27-10 : Missing Number
dscigdtuw/DSA pull request #35
Opened 2020-10-28 16:29 UTC by IshaSethi3011

2020-10-30 16:06 UTC, nancysolanki approved these changes

2020-10-30 16:07 UTC, nancysolanki approved these changes

2020-10-30 16:08 UTC, nancysolanki approved these changes

2020-10-30 16:08 UTC, nancysolanki approved these changes

2020-10-30 16:09 UTC, nancysolanki approved these changes

2020-10-30 16:10 UTC, nancysolanki approved these changes

2020-10-30 16:10 UTC, nancysolanki approved these changes

2020-10-30 16:11 UTC, nancysolanki approved these changes

2020-11-02 19:49 UTC, raksha009 requested changes
Hey!, Its from main branch

2020-11-03 05:17 UTC, nancysolanki approved these changes

2020-11-03 05:17 UTC, nancysolanki approved these changes

2020-11-03 19:33 UTC, raksha009 reviewed
Hey, you have created a pr from yr main branch. Closing it for now. Plz create another br from another branch and do tag this pr too there.

2020-11-03 19:33 UTC, closed without merging